name: ${APP_NAME}

services:
  old_chinook_db:
    container_name: old_chinook
    image: postgres:16
    ports:
      - "${OLD_OUT_PORT}:5432"
    volumes:
      - chinook_old_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${OLD_DATABASE}
      - POSTGRES_USER=${OLD_USERNAME}
      - POSTGRES_PASSWORD=${OLD_PASSWORD}
    networks:
      - db_migrate_network

  new_chinook_db:
    container_name: new_chinook
    image: postgres:16
    ports:
      - "${NEW_OUT_PORT}:5432"
    volumes:
      - chinook_new_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NEW_DATABASE}
      - POSTGRES_USER=${NEW_USERNAME}
      - POSTGRES_PASSWORD=${NEW_PASSWORD}
    networks:
      - db_migrate_network

volumes:
  chinook_old_data:
    name: chinook_old_data
    external: true
  chinook_new_data:
    name: chinook_new_data
    external: true

networks:
  db_migrate_network:
    driver: bridge
    name: db_migrate_network
    external: true
