version: "3.8"
name: ${APP_NAME}

services:
  old_publication_db:
    container_name: old_publication
    image: postgres:16
    ports:
      - "${OLD_OUT_PORT}:5432"
    volumes:
      - publication_old_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${OLD_DATABASE}
      - POSTGRES_USER=${OLD_USERNAME}
      - POSTGRES_PASSWORD=${OLD_PASSWORD}
    networks:
      - db_migrate_network

  new_publication_db:
    container_name: new_publication
    image: postgres:16
    ports:
      - "${NEW_OUT_PORT}:5432"
    volumes:
      - publication_new_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NEW_DATABASE}
      - POSTGRES_USER=${NEW_USERNAME}
      - POSTGRES_PASSWORD=${NEW_PASSWORD}
    networks:
      - db_migrate_network

volumes:
  publication_old_data:
    external: true
  publication_new_data:
    external: true

networks:
  db_migrate_network:
    driver: bridge
    name: db_migrate_network
    external: true
