CREATE TABLE "customers" (
  "id" SERIAL PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "phone" varchar UNIQUE,
  "address" varchar,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "orders" (
  "id" SERIAL PRIMARY KEY,
  "customer_id" int,
  "status" varchar,
  "delivery_type" varchar,
  "total_amount" int,
  "grand_total" int,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "order_items" (
  "id" SERIAL PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "quantity" int,
  "price_per_item" int,
  "total_amount" int,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "products" (
  "id" SERIAL PRIMARY KEY,
  "name" varchar NOT NULL,
  "price" int NOT NULL,
  "description" varchar,
  "product_category_id" int,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "product_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "payments" (
  "id" SERIAL PRIMARY KEY,
  "customer_id" int,
  "order_id" int,
  "status" varchar,
  "payment_fee" int,
  "total_amount" int,
  "grand_total" int,
  "created_at" timestamptz DEFAULT (now())
);


ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("product_category_id") REFERENCES "product_categories" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");