@startuml CheckerFlow
title Checker Worker

start
  repeat
:Get multiple rows in _exec_queue table;
:Take One Row;
    
      :Parse fact payload;
      :Find entity in planner;
      :Get dim fragments for join_key\n(from _join_map_topic);
    
      if (need_keymap?) then (yes)
        :Parse keymap_payload;
        :Ensure map_name and src_key exist;
        if (Invalid payload?) then (yes)
          :Mark row error;
        else (ok)
          :Ensure keymap request exists\nin _keymap_generic table;
          :Attach keymap_id, mark ready;
        endif
      else (no keymap)
        :Mark row ready;
      endif
    
  repeat while (Next Batch)

stop
@enduml
  :Sleep until next tick;
