@startuml ExecutorFlow
title Executor Worker

start
  repeat
:Fetch multiple ready rows from _exec_queue;
  :Begin target DB transaction;
    :Read a row;
      if (Need keymap and has RETURNING?) then (yes)
        :Run QueryRow;
        if (SQL failed?) then (yes)
          :Mark row error;\n(if keymap) mark keymap error;
        else (ok)
          :Capture returning key and fulfill keymap;
          :Mark row done;
        endif
      else (no keymap return)
        :Run Exec;
        if (SQL failed?) then (yes)
          :Mark row error;
        else (ok)
          :Mark row done;
        endif
      endif
  repeat while (next batch)

@enduml
