@startuml ParserFlow
title Parser Worker

start
repeat
:Receive Kafka event\nconsist topic & payload;
if (\nCheck the event\nmatch to entities?\n) then (yes)
    :Get entity mapping;
    if (Check fact event condition passes?) then (yes)
      if (Entity needs join?) then (yes)
        if (Event is fact topic?) then (yes, fact event)
          :Store event payload join and\nentity datain _need_join table;
        else (no, dim topic)
          :Store event payload\nin _join_map table;
          :Store event payload\nin _join_map_topic table;
        endif
      else (no)
        :Enqueue SQL job to _exec_queue\n(need_keymap? returning? args JSON);
        if (Entity has split tables?) then (yes)
          :Enqueue split inserts\nlinked to queue_id;
        endif
      endif
    else (no)
      :Skip entity;
    endif
else (no)
  :No entity matched;
  :Skip to next event;
endif
repeat while (Next Event)

stop
@enduml
